spring.application.name=springBootTutorial
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/D/ignite/springBootDb/db
spring.datasource.username=sudhaDb
spring.datasource.password=sudha123
spring.jpa.hibernate.ddl-auto=create
